<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Statistical Methods II</title>
  <meta name="description" content="The second semester of an Intro Stats course designed for graduate students in Biology, Forestry, Ecology, etc.">
  <meta name="generator" content="bookdown 0.7 and GitBook 2.6.7">

  <meta property="og:title" content="Statistical Methods II" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="The second semester of an Intro Stats course designed for graduate students in Biology, Forestry, Ecology, etc." />
  <meta name="github-repo" content="dereksonderegger/STA_571_Book" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Statistical Methods II" />
  
  <meta name="twitter:description" content="The second semester of an Intro Stats course designed for graduate students in Biology, Forestry, Ecology, etc." />
  

<meta name="author" content="Derek L. Sonderegger">


<meta name="date" content="2018-04-17">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="4-analysis-of-covariance-ancova.html">
<link rel="next" href="6-diagnostics-and-transformations.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Statistical Methods II</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="1-matrix-theory.html"><a href="1-matrix-theory.html"><i class="fa fa-check"></i><b>1</b> Matrix Theory</a><ul>
<li class="chapter" data-level="1.1" data-path="1-matrix-theory.html"><a href="1-matrix-theory.html#types-of-matrices"><i class="fa fa-check"></i><b>1.1</b> Types of Matrices</a><ul>
<li class="chapter" data-level="1.1.1" data-path="1-matrix-theory.html"><a href="1-matrix-theory.html#scalars"><i class="fa fa-check"></i><b>1.1.1</b> Scalars</a></li>
<li class="chapter" data-level="1.1.2" data-path="1-matrix-theory.html"><a href="1-matrix-theory.html#vectors"><i class="fa fa-check"></i><b>1.1.2</b> Vectors</a></li>
<li class="chapter" data-level="1.1.3" data-path="1-matrix-theory.html"><a href="1-matrix-theory.html#matrix"><i class="fa fa-check"></i><b>1.1.3</b> Matrix</a></li>
<li class="chapter" data-level="1.1.4" data-path="1-matrix-theory.html"><a href="1-matrix-theory.html#square-matrices"><i class="fa fa-check"></i><b>1.1.4</b> Square Matrices</a></li>
<li class="chapter" data-level="1.1.5" data-path="1-matrix-theory.html"><a href="1-matrix-theory.html#symmetric-matrices"><i class="fa fa-check"></i><b>1.1.5</b> Symmetric Matrices</a></li>
<li class="chapter" data-level="1.1.6" data-path="1-matrix-theory.html"><a href="1-matrix-theory.html#diagonal-matrices"><i class="fa fa-check"></i><b>1.1.6</b> Diagonal Matrices</a></li>
<li class="chapter" data-level="1.1.7" data-path="1-matrix-theory.html"><a href="1-matrix-theory.html#identity-matrices"><i class="fa fa-check"></i><b>1.1.7</b> Identity Matrices</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="1-matrix-theory.html"><a href="1-matrix-theory.html#operations-on-matrices"><i class="fa fa-check"></i><b>1.2</b> Operations on Matrices</a><ul>
<li class="chapter" data-level="1.2.1" data-path="1-matrix-theory.html"><a href="1-matrix-theory.html#transpose"><i class="fa fa-check"></i><b>1.2.1</b> Transpose</a></li>
<li class="chapter" data-level="1.2.2" data-path="1-matrix-theory.html"><a href="1-matrix-theory.html#addition-and-subtraction"><i class="fa fa-check"></i><b>1.2.2</b> Addition and Subtraction</a></li>
<li class="chapter" data-level="1.2.3" data-path="1-matrix-theory.html"><a href="1-matrix-theory.html#multiplication"><i class="fa fa-check"></i><b>1.2.3</b> Multiplication</a></li>
<li class="chapter" data-level="1.2.4" data-path="1-matrix-theory.html"><a href="1-matrix-theory.html#vector-multiplication"><i class="fa fa-check"></i><b>1.2.4</b> Vector Multiplication</a></li>
<li class="chapter" data-level="1.2.5" data-path="1-matrix-theory.html"><a href="1-matrix-theory.html#matrix-multiplication"><i class="fa fa-check"></i><b>1.2.5</b> Matrix Multiplication</a></li>
<li class="chapter" data-level="1.2.6" data-path="1-matrix-theory.html"><a href="1-matrix-theory.html#scalar-times-a-matrix"><i class="fa fa-check"></i><b>1.2.6</b> Scalar times a Matrix</a></li>
<li class="chapter" data-level="1.2.7" data-path="1-matrix-theory.html"><a href="1-matrix-theory.html#determinant"><i class="fa fa-check"></i><b>1.2.7</b> Determinant</a></li>
<li class="chapter" data-level="1.2.8" data-path="1-matrix-theory.html"><a href="1-matrix-theory.html#inverse"><i class="fa fa-check"></i><b>1.2.8</b> Inverse</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="1-matrix-theory.html"><a href="1-matrix-theory.html#exercises"><i class="fa fa-check"></i><b>1.3</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="2-parameter-estimation.html"><a href="2-parameter-estimation.html"><i class="fa fa-check"></i><b>2</b> Parameter Estimation</a><ul>
<li class="chapter" data-level="2.1" data-path="2-parameter-estimation.html"><a href="2-parameter-estimation.html#simple-regression"><i class="fa fa-check"></i><b>2.1</b> Simple Regression</a><ul>
<li class="chapter" data-level="2.1.1" data-path="2-parameter-estimation.html"><a href="2-parameter-estimation.html#estimation-of-location-paramters"><i class="fa fa-check"></i><b>2.1.1</b> Estimation of Location Paramters</a></li>
<li class="chapter" data-level="2.1.2" data-path="2-parameter-estimation.html"><a href="2-parameter-estimation.html#estimation-of-variance-parameter"><i class="fa fa-check"></i><b>2.1.2</b> Estimation of Variance Parameter</a></li>
<li class="chapter" data-level="2.1.3" data-path="2-parameter-estimation.html"><a href="2-parameter-estimation.html#expectation-and-variance-of-a-random-vector"><i class="fa fa-check"></i><b>2.1.3</b> Expectation and variance of a random vector</a></li>
<li class="chapter" data-level="2.1.4" data-path="2-parameter-estimation.html"><a href="2-parameter-estimation.html#variance-of-location-parameters"><i class="fa fa-check"></i><b>2.1.4</b> Variance of Location Parameters</a></li>
<li class="chapter" data-level="2.1.5" data-path="2-parameter-estimation.html"><a href="2-parameter-estimation.html#confidence-intervals-and-hypothesis-tests"><i class="fa fa-check"></i><b>2.1.5</b> Confidence intervals and hypothesis tests</a></li>
<li class="chapter" data-level="2.1.6" data-path="2-parameter-estimation.html"><a href="2-parameter-estimation.html#summary-of-pertinent-results"><i class="fa fa-check"></i><b>2.1.6</b> Summary of pertinent results</a></li>
<li class="chapter" data-level="2.1.7" data-path="2-parameter-estimation.html"><a href="2-parameter-estimation.html#an-example-in-r"><i class="fa fa-check"></i><b>2.1.7</b> An example in R</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="2-parameter-estimation.html"><a href="2-parameter-estimation.html#anova-model"><i class="fa fa-check"></i><b>2.2</b> ANOVA model</a><ul>
<li class="chapter" data-level="2.2.1" data-path="2-parameter-estimation.html"><a href="2-parameter-estimation.html#cell-means-representation"><i class="fa fa-check"></i><b>2.2.1</b> Cell means representation</a></li>
<li class="chapter" data-level="2.2.2" data-path="2-parameter-estimation.html"><a href="2-parameter-estimation.html#offset-from-reference-group"><i class="fa fa-check"></i><b>2.2.2</b> Offset from reference group</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="2-parameter-estimation.html"><a href="2-parameter-estimation.html#exercises-1"><i class="fa fa-check"></i><b>2.3</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="3-inference.html"><a href="3-inference.html"><i class="fa fa-check"></i><b>3</b> Inference</a><ul>
<li class="chapter" data-level="3.1" data-path="3-inference.html"><a href="3-inference.html#f-tests"><i class="fa fa-check"></i><b>3.1</b> F-tests</a><ul>
<li class="chapter" data-level="3.1.1" data-path="3-inference.html"><a href="3-inference.html#theory"><i class="fa fa-check"></i><b>3.1.1</b> Theory</a></li>
<li class="chapter" data-level="3.1.2" data-path="3-inference.html"><a href="3-inference.html#testing-all-covariates"><i class="fa fa-check"></i><b>3.1.2</b> Testing All Covariates</a></li>
<li class="chapter" data-level="3.1.3" data-path="3-inference.html"><a href="3-inference.html#testing-a-single-covariate"><i class="fa fa-check"></i><b>3.1.3</b> Testing a Single Covariate</a></li>
<li class="chapter" data-level="3.1.4" data-path="3-inference.html"><a href="3-inference.html#testing-a-subset-of-covariates"><i class="fa fa-check"></i><b>3.1.4</b> Testing a Subset of Covariates</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="3-inference.html"><a href="3-inference.html#confidence-intervals-for-location-parameters"><i class="fa fa-check"></i><b>3.2</b> Confidence Intervals for location parameters</a></li>
<li class="chapter" data-level="3.3" data-path="3-inference.html"><a href="3-inference.html#prediction-and-confidence-intervals-for-a-response"><i class="fa fa-check"></i><b>3.3</b> Prediction and Confidence Intervals for a response</a></li>
<li class="chapter" data-level="3.4" data-path="3-inference.html"><a href="3-inference.html#interpretation-with-correlated-covariates"><i class="fa fa-check"></i><b>3.4</b> Interpretation with Correlated Covariates</a></li>
<li class="chapter" data-level="3.5" data-path="3-inference.html"><a href="3-inference.html#exercises-2"><i class="fa fa-check"></i><b>3.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="4-analysis-of-covariance-ancova.html"><a href="4-analysis-of-covariance-ancova.html"><i class="fa fa-check"></i><b>4</b> Analysis of Covariance (ANCOVA)</a><ul>
<li class="chapter" data-level="4.1" data-path="4-analysis-of-covariance-ancova.html"><a href="4-analysis-of-covariance-ancova.html#offset-parallel-lines-aka-additive-models"><i class="fa fa-check"></i><b>4.1</b> Offset parallel Lines (aka additive models)</a></li>
<li class="chapter" data-level="4.2" data-path="4-analysis-of-covariance-ancova.html"><a href="4-analysis-of-covariance-ancova.html#lines-with-different-slopes-aka-interaction-model"><i class="fa fa-check"></i><b>4.2</b> Lines with different slopes (aka Interaction model)</a></li>
<li class="chapter" data-level="4.3" data-path="4-analysis-of-covariance-ancova.html"><a href="4-analysis-of-covariance-ancova.html#iris-example"><i class="fa fa-check"></i><b>4.3</b> Iris Example</a></li>
<li class="chapter" data-level="4.4" data-path="4-analysis-of-covariance-ancova.html"><a href="4-analysis-of-covariance-ancova.html#exercises-3"><i class="fa fa-check"></i><b>4.4</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="5-contrasts.html"><a href="5-contrasts.html"><i class="fa fa-check"></i><b>5</b> Contrasts</a><ul>
<li class="chapter" data-level="5.1" data-path="5-contrasts.html"><a href="5-contrasts.html#estimate-and-variance"><i class="fa fa-check"></i><b>5.1</b> Estimate and variance</a></li>
<li class="chapter" data-level="5.2" data-path="5-contrasts.html"><a href="5-contrasts.html#estimating-contrasts-using-glht"><i class="fa fa-check"></i><b>5.2</b> Estimating contrasts using <code>glht()</code></a><ul>
<li class="chapter" data-level="5.2.1" data-path="5-contrasts.html"><a href="5-contrasts.html#way-anova"><i class="fa fa-check"></i><b>5.2.1</b> 1-way ANOVA</a></li>
<li class="chapter" data-level="5.2.2" data-path="5-contrasts.html"><a href="5-contrasts.html#ancova-example"><i class="fa fa-check"></i><b>5.2.2</b> ANCOVA example</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="5-contrasts.html"><a href="5-contrasts.html#using-emmeans-package"><i class="fa fa-check"></i><b>5.3</b> Using <code>emmeans</code> Package</a><ul>
<li class="chapter" data-level="5.3.1" data-path="5-contrasts.html"><a href="5-contrasts.html#simple-regression-1"><i class="fa fa-check"></i><b>5.3.1</b> Simple Regression</a></li>
<li class="chapter" data-level="5.3.2" data-path="5-contrasts.html"><a href="5-contrasts.html#way-anova-1"><i class="fa fa-check"></i><b>5.3.2</b> 1-way ANOVA</a></li>
<li class="chapter" data-level="5.3.3" data-path="5-contrasts.html"><a href="5-contrasts.html#ancova"><i class="fa fa-check"></i><b>5.3.3</b> ANCOVA</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="5-contrasts.html"><a href="5-contrasts.html#exercises-4"><i class="fa fa-check"></i><b>5.4</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="6-diagnostics-and-transformations.html"><a href="6-diagnostics-and-transformations.html"><i class="fa fa-check"></i><b>6</b> Diagnostics and Transformations</a><ul>
<li class="chapter" data-level="6.1" data-path="6-diagnostics-and-transformations.html"><a href="6-diagnostics-and-transformations.html#detecting-assumption-violations"><i class="fa fa-check"></i><b>6.1</b> Detecting Assumption Violations</a><ul>
<li class="chapter" data-level="6.1.1" data-path="6-diagnostics-and-transformations.html"><a href="6-diagnostics-and-transformations.html#measures-of-influence"><i class="fa fa-check"></i><b>6.1.1</b> Measures of Influence</a></li>
<li class="chapter" data-level="6.1.2" data-path="6-diagnostics-and-transformations.html"><a href="6-diagnostics-and-transformations.html#diagnostic-plots"><i class="fa fa-check"></i><b>6.1.2</b> Diagnostic Plots</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="6-diagnostics-and-transformations.html"><a href="6-diagnostics-and-transformations.html#transformations"><i class="fa fa-check"></i><b>6.2</b> Transformations</a><ul>
<li class="chapter" data-level="6.2.1" data-path="6-diagnostics-and-transformations.html"><a href="6-diagnostics-and-transformations.html#a-review-of-logx-and-ex"><i class="fa fa-check"></i><b>6.2.1</b> A review of <span class="math inline">\(\log(x)\)</span> and <span class="math inline">\(e^x\)</span></a></li>
<li class="chapter" data-level="6.2.2" data-path="6-diagnostics-and-transformations.html"><a href="6-diagnostics-and-transformations.html#transforming-the-response"><i class="fa fa-check"></i><b>6.2.2</b> Transforming the Response</a></li>
<li class="chapter" data-level="6.2.3" data-path="6-diagnostics-and-transformations.html"><a href="6-diagnostics-and-transformations.html#transforming-the-predictors"><i class="fa fa-check"></i><b>6.2.3</b> Transforming the predictors</a></li>
<li class="chapter" data-level="6.2.4" data-path="6-diagnostics-and-transformations.html"><a href="6-diagnostics-and-transformations.html#interpretation-of-log-transformed-variables"><i class="fa fa-check"></i><b>6.2.4</b> Interpretation of log transformed variables</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="6-diagnostics-and-transformations.html"><a href="6-diagnostics-and-transformations.html#exercises-5"><i class="fa fa-check"></i><b>6.3</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="7-variable-selection.html"><a href="7-variable-selection.html"><i class="fa fa-check"></i><b>7</b> Variable Selection</a><ul>
<li class="chapter" data-level="7.1" data-path="7-variable-selection.html"><a href="7-variable-selection.html#nested-models"><i class="fa fa-check"></i><b>7.1</b> Nested Models</a></li>
<li class="chapter" data-level="7.2" data-path="7-variable-selection.html"><a href="7-variable-selection.html#testing-based-model-selection"><i class="fa fa-check"></i><b>7.2</b> Testing-Based Model Selection</a><ul>
<li class="chapter" data-level="7.2.1" data-path="7-variable-selection.html"><a href="7-variable-selection.html#example---u.s.-life-expectancy"><i class="fa fa-check"></i><b>7.2.1</b> Example - U.S. Life Expectancy</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="7-variable-selection.html"><a href="7-variable-selection.html#criterion-based-procedures"><i class="fa fa-check"></i><b>7.3</b> Criterion Based Procedures</a><ul>
<li class="chapter" data-level="7.3.1" data-path="7-variable-selection.html"><a href="7-variable-selection.html#information-criterions"><i class="fa fa-check"></i><b>7.3.1</b> Information Criterions</a></li>
<li class="chapter" data-level="7.3.2" data-path="7-variable-selection.html"><a href="7-variable-selection.html#adjusted-r-sq"><i class="fa fa-check"></i><b>7.3.2</b> Adjusted <code>R-sq</code></a></li>
<li class="chapter" data-level="7.3.3" data-path="7-variable-selection.html"><a href="7-variable-selection.html#example"><i class="fa fa-check"></i><b>7.3.3</b> Example</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="7-variable-selection.html"><a href="7-variable-selection.html#exercises-6"><i class="fa fa-check"></i><b>7.4</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="8-one-way-anova.html"><a href="8-one-way-anova.html"><i class="fa fa-check"></i><b>8</b> One way ANOVA</a><ul>
<li class="chapter" data-level="8.1" data-path="8-one-way-anova.html"><a href="8-one-way-anova.html#an-example"><i class="fa fa-check"></i><b>8.1</b> An Example</a></li>
<li class="chapter" data-level="8.2" data-path="8-one-way-anova.html"><a href="8-one-way-anova.html#degrees-of-freedom"><i class="fa fa-check"></i><b>8.2</b> Degrees of Freedom</a></li>
<li class="chapter" data-level="8.3" data-path="8-one-way-anova.html"><a href="8-one-way-anova.html#diagnostics"><i class="fa fa-check"></i><b>8.3</b> Diagnostics</a></li>
<li class="chapter" data-level="8.4" data-path="8-one-way-anova.html"><a href="8-one-way-anova.html#pairwise-comparisons"><i class="fa fa-check"></i><b>8.4</b> Pairwise Comparisons</a></li>
<li class="chapter" data-level="8.5" data-path="8-one-way-anova.html"><a href="8-one-way-anova.html#exercises-7"><i class="fa fa-check"></i><b>8.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="9-two-way-anova.html"><a href="9-two-way-anova.html"><i class="fa fa-check"></i><b>9</b> Two-way ANOVA</a><ul>
<li class="chapter" data-level="9.1" data-path="9-two-way-anova.html"><a href="9-two-way-anova.html#orthogonality"><i class="fa fa-check"></i><b>9.1</b> Orthogonality</a></li>
<li class="chapter" data-level="9.2" data-path="9-two-way-anova.html"><a href="9-two-way-anova.html#main-effects-model"><i class="fa fa-check"></i><b>9.2</b> Main Effects Model</a><ul>
<li class="chapter" data-level="9.2.1" data-path="9-two-way-anova.html"><a href="9-two-way-anova.html#example---fruit-trees"><i class="fa fa-check"></i><b>9.2.1</b> Example - Fruit Trees</a></li>
<li class="chapter" data-level="9.2.2" data-path="9-two-way-anova.html"><a href="9-two-way-anova.html#anova-table"><i class="fa fa-check"></i><b>9.2.2</b> ANOVA Table</a></li>
<li class="chapter" data-level="9.2.3" data-path="9-two-way-anova.html"><a href="9-two-way-anova.html#estimating-contrasts"><i class="fa fa-check"></i><b>9.2.3</b> Estimating Contrasts</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="9-two-way-anova.html"><a href="9-two-way-anova.html#interaction-model"><i class="fa fa-check"></i><b>9.3</b> Interaction Model</a><ul>
<li class="chapter" data-level="9.3.1" data-path="9-two-way-anova.html"><a href="9-two-way-anova.html#anova-table-1"><i class="fa fa-check"></i><b>9.3.1</b> ANOVA Table</a></li>
<li class="chapter" data-level="9.3.2" data-path="9-two-way-anova.html"><a href="9-two-way-anova.html#example---fruit-trees-continued"><i class="fa fa-check"></i><b>9.3.2</b> Example - Fruit Trees (continued)</a></li>
<li class="chapter" data-level="9.3.3" data-path="9-two-way-anova.html"><a href="9-two-way-anova.html#example---warpbreaks"><i class="fa fa-check"></i><b>9.3.3</b> Example - Warpbreaks</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="9-two-way-anova.html"><a href="9-two-way-anova.html#exercises-8"><i class="fa fa-check"></i><b>9.4</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="10-block-designs.html"><a href="10-block-designs.html"><i class="fa fa-check"></i><b>10</b> Block Designs</a><ul>
<li class="chapter" data-level="10.1" data-path="10-block-designs.html"><a href="10-block-designs.html#randomized-complete-block-design-rcbd"><i class="fa fa-check"></i><b>10.1</b> Randomized Complete Block Design (RCBD)</a></li>
<li class="chapter" data-level="10.2" data-path="10-block-designs.html"><a href="10-block-designs.html#split-plot-designs"><i class="fa fa-check"></i><b>10.2</b> Split-plot designs</a></li>
<li class="chapter" data-level="10.3" data-path="10-block-designs.html"><a href="10-block-designs.html#exercises-9"><i class="fa fa-check"></i><b>10.3</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="11-mixed-effects-models.html"><a href="11-mixed-effects-models.html"><i class="fa fa-check"></i><b>11</b> Mixed Effects Models</a><ul>
<li class="chapter" data-level="11.1" data-path="11-mixed-effects-models.html"><a href="11-mixed-effects-models.html#review-of-maximum-likelihood-methods"><i class="fa fa-check"></i><b>11.1</b> Review of Maximum Likelihood Methods</a></li>
<li class="chapter" data-level="11.2" data-path="11-mixed-effects-models.html"><a href="11-mixed-effects-models.html#way-anova-with-a-random-effect"><i class="fa fa-check"></i><b>11.2</b> 1-way ANOVA with a random effect</a></li>
<li class="chapter" data-level="11.3" data-path="11-mixed-effects-models.html"><a href="11-mixed-effects-models.html#blocks-as-random-variables"><i class="fa fa-check"></i><b>11.3</b> Blocks as Random Variables</a></li>
<li class="chapter" data-level="11.4" data-path="11-mixed-effects-models.html"><a href="11-mixed-effects-models.html#nested-effects"><i class="fa fa-check"></i><b>11.4</b> Nested Effects</a></li>
<li class="chapter" data-level="11.5" data-path="11-mixed-effects-models.html"><a href="11-mixed-effects-models.html#crossed-effects"><i class="fa fa-check"></i><b>11.5</b> Crossed Effects</a></li>
<li class="chapter" data-level="11.6" data-path="11-mixed-effects-models.html"><a href="11-mixed-effects-models.html#repeated-measures-longitudinal-studies"><i class="fa fa-check"></i><b>11.6</b> Repeated Measures / Longitudinal Studies</a></li>
<li class="chapter" data-level="11.7" data-path="11-mixed-effects-models.html"><a href="11-mixed-effects-models.html#exercises-10"><i class="fa fa-check"></i><b>11.7</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="12-binomial-regression.html"><a href="12-binomial-regression.html"><i class="fa fa-check"></i><b>12</b> Binomial Regression</a><ul>
<li class="chapter" data-level="12.1" data-path="12-binomial-regression.html"><a href="12-binomial-regression.html#binomial-regression-model"><i class="fa fa-check"></i><b>12.1</b> Binomial Regression Model</a></li>
<li class="chapter" data-level="12.2" data-path="12-binomial-regression.html"><a href="12-binomial-regression.html#measures-of-fit-quality"><i class="fa fa-check"></i><b>12.2</b> Measures of Fit Quality</a><ul>
<li class="chapter" data-level="12.2.1" data-path="12-binomial-regression.html"><a href="12-binomial-regression.html#deviance"><i class="fa fa-check"></i><b>12.2.1</b> Deviance</a></li>
<li class="chapter" data-level="12.2.2" data-path="12-binomial-regression.html"><a href="12-binomial-regression.html#goodness-of-fit"><i class="fa fa-check"></i><b>12.2.2</b> Goodness of Fit</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="12-binomial-regression.html"><a href="12-binomial-regression.html#confidence-intervals"><i class="fa fa-check"></i><b>12.3</b> Confidence Intervals</a></li>
<li class="chapter" data-level="12.4" data-path="12-binomial-regression.html"><a href="12-binomial-regression.html#interpreting-model-coefficients"><i class="fa fa-check"></i><b>12.4</b> Interpreting model coefficients</a></li>
<li class="chapter" data-level="12.5" data-path="12-binomial-regression.html"><a href="12-binomial-regression.html#prediction-and-effective-dose-levels"><i class="fa fa-check"></i><b>12.5</b> Prediction and Effective Dose Levels</a></li>
<li class="chapter" data-level="12.6" data-path="12-binomial-regression.html"><a href="12-binomial-regression.html#overdispersion"><i class="fa fa-check"></i><b>12.6</b> Overdispersion</a></li>
<li class="chapter" data-level="12.7" data-path="12-binomial-regression.html"><a href="12-binomial-regression.html#roc-curves"><i class="fa fa-check"></i><b>12.7</b> ROC Curves</a></li>
<li class="chapter" data-level="12.8" data-path="12-binomial-regression.html"><a href="12-binomial-regression.html#exercises-11"><i class="fa fa-check"></i><b>12.8</b> Exercises</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Statistical Methods II</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="contrasts" class="section level1">
<h1><span class="header-section-number">Chapter 5</span> Contrasts</h1>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(tidyverse)  <span class="co"># ggplot2, dplyr, tidyr</span>
<span class="kw">library</span>(emmeans)    <span class="co"># for emmeans()</span>
<span class="kw">library</span>(multcomp)   <span class="co"># for glht() </span></code></pre></div>
<p>We often are interested in estimating a function of the parameters <span class="math inline">\(\boldsymbol{\beta}\)</span>. For example in the offset representation of the ANOVA model with 3 groups we have <span class="math display">\[y_{ij}=\mu+\tau_{i}+\epsilon_{ij}\]</span> where <span class="math display">\[
\boldsymbol{\beta}=\left[\mu\;\tau_{2}\;\tau_{3}\right]^{T}
\]</span> and <span class="math inline">\(\mu\)</span> is the mean of the control group, group one is the control group and thus <span class="math inline">\(\tau_{1}=0\)</span>, and <span class="math inline">\(\tau_{2}\)</span> and <span class="math inline">\(\tau_{3}\)</span> are the offsets of group two and three from the control group. In this representation, the mean of group two is <span class="math inline">\(\mu+\tau_{2}\)</span> and is estimated with <span class="math inline">\(\hat{\mu} + \hat{\tau}_2\)</span>.</p>
<div id="estimate-and-variance" class="section level2">
<h2><span class="header-section-number">5.1</span> Estimate and variance</h2>
<p>A contrast is a linear combinations of elements of <span class="math inline">\(\boldsymbol{\hat{\beta}}\)</span>, which is a fancy way of saying that it is a function of the elements of <span class="math inline">\(\boldsymbol{\hat{\beta}}\)</span> where the elements can be added, subtracted, or multiplied by constants. In particular, the contrast can be represented by the vector <span class="math inline">\(\boldsymbol{c}\)</span> such that the function we are interested in is <span class="math inline">\(\boldsymbol{c}^{T}\boldsymbol{\hat{\beta}}\)</span>.</p>
<p>In the ANOVA case with <span class="math inline">\(k=3\)</span> where we have the offset representation, I might be interested in the mean of group 2, which could be written as <span class="math display">\[
\mu+\tau_{2}=\underset{\boldsymbol{c}^{T}}{\underbrace{\left[\begin{array}{ccc}
1 &amp; 1 &amp; 0\end{array}\right]}}\cdot\underset{\hat{\boldsymbol{\beta}}}{\underbrace{\left[\begin{array}{c}
\hat{\mu}\\
\hat{\tau_{2}}\\
\hat{\tau_{3}}
\end{array}\right]}}
\]</span></p>
<p>Similarly in the simple regression case, I will be interested in the height of the regression line at <span class="math inline">\(x_0\)</span>. This height can be written as<br />
<span class="math display">\[
\hat{\beta}_{0}+\hat{\beta}_{1}x_{0}=\underset{\boldsymbol{c}^{T}}{\underbrace{\left[\begin{array}{cc}
1 &amp; x_{0}\end{array}\right]}}\cdot\underset{\hat{\boldsymbol{\beta}}}{\underbrace{\left[\begin{array}{c}
\hat{\beta}_{0}\\
\hat{\beta}_{1}
\end{array}\right]}}
\]</span> In this manner, we could think of the predicted values <span class="math inline">\(\hat{y}_i\)</span> as just the result of the contrasts <span class="math inline">\(\boldsymbol{X} \hat{\boldsymbol{\beta}}\)</span> where our design matrix takes the role of the contrasts.</p>
<p>One of the properties of maximum likelihood estimator (MLEs), is that they are invariant under transformations. Meaning that since <span class="math inline">\(\hat{\boldsymbol{\beta}}\)</span> is the MLE of <span class="math inline">\(\boldsymbol{\beta}\)</span>, then <span class="math inline">\(\boldsymbol{c}^{T}\hat{\boldsymbol{\beta}}\)</span> is the MLE of <span class="math inline">\(\boldsymbol{c}^{T}\boldsymbol{\beta}\)</span>. The only thing we need to perform hypotheses tests and create confidence intervals is an estimate of the variance of <span class="math inline">\(\boldsymbol{c}^{T}\hat{\boldsymbol{\beta}}\)</span>.</p>
<p>Because we know the variance of <span class="math inline">\(\hat{\boldsymbol{\beta}}\)</span> is <span class="math display">\[
Var\left(\hat{\boldsymbol{\beta}}\right)=\sigma^{2}\left(\boldsymbol{X}^{T}\boldsymbol{X}\right)^{-1}
\]</span> and because <span class="math inline">\(\boldsymbol{c}\)</span> is a constant, then <span class="math display">\[
Var\left(\boldsymbol{c}^{T}\hat{\boldsymbol{\beta}}\right)=\sigma^{2}\boldsymbol{c}^{T}\left(\boldsymbol{X}^{T}\boldsymbol{X}\right)^{-1}\boldsymbol{c}
\]</span> and the standard error is found by plugging in our estimate of <span class="math inline">\(\sigma^{2}\)</span> and taking the square root. <span class="math display">\[
StdErr\left(\boldsymbol{c}^{T}\hat{\boldsymbol{\beta}}\right)   =   \sqrt{\hat{\sigma}^{2}\boldsymbol{c}^{T}\left(\boldsymbol{X}^{T}\boldsymbol{X}\right)^{-1}\boldsymbol{c}}
    =   \hat{\sigma}\sqrt{\boldsymbol{c}^{T}\left(\boldsymbol{X}^{T}\boldsymbol{X}\right)^{-1}\boldsymbol{c}}
\]</span></p>
<p>As usual, we can now calculate confidence intervals for <span class="math inline">\(\boldsymbol{c}^{T}\hat{\boldsymbol{\beta}}\)</span> using the usual formula <span class="math display">\[Est   \pm t_{n-p}^{1-\alpha/2}\;StdErr\left(\,Est\,\right)\]</span> <span class="math display">\[
\boldsymbol{c}^{T}\hat{\boldsymbol{\beta}}  \pm t_{n-p}^{1-\alpha/2}\;\hat{\sigma}\sqrt{\boldsymbol{c}^{T}\left(\boldsymbol{X}^{T}\boldsymbol{X}\right)^{-1}\boldsymbol{c}}
\]</span></p>
<p>Recall the hostility example which was an ANOVA with three groups with the data</p>
<table>
<thead>
<tr class="header">
<th>Method</th>
<th>Test Scores</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>96 79 91 85 83 91 82 87</td>
</tr>
<tr class="even">
<td>2</td>
<td>77 76 74 73 78 71 80</td>
</tr>
<tr class="odd">
<td>3</td>
<td>66 73 69 66 77 73 71 70 74</td>
</tr>
</tbody>
</table>
<p>We have analyzed this data using both the cell means model and the offset and we will demonstrate how to calculate the group means from the offset representation. Thus we are interested in estimating <span class="math inline">\(\mu+\tau_{2}\)</span> and <span class="math inline">\(\mu+\tau_{3}\)</span>. I am also interested in estimating the difference between treatment 2 and 3 and will therefore be interested in estimating <span class="math inline">\(\tau_{2} - \tau_{3}\)</span>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">y &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">96</span>,<span class="dv">79</span>,<span class="dv">91</span>,<span class="dv">85</span>,<span class="dv">83</span>,<span class="dv">91</span>,<span class="dv">82</span>,<span class="dv">87</span>,
       <span class="dv">77</span>,<span class="dv">76</span>,<span class="dv">74</span>,<span class="dv">73</span>,<span class="dv">78</span>,<span class="dv">71</span>,<span class="dv">80</span>,
       <span class="dv">66</span>,<span class="dv">73</span>,<span class="dv">69</span>,<span class="dv">66</span>,<span class="dv">77</span>,<span class="dv">73</span>,<span class="dv">71</span>,<span class="dv">70</span>,<span class="dv">74</span>)
groups &lt;-<span class="st"> </span><span class="kw">factor</span>(<span class="kw">c</span>( <span class="kw">rep</span>(<span class="st">&#39;Group1&#39;</span>,<span class="dv">8</span>), <span class="kw">rep</span>(<span class="st">&#39;Group2&#39;</span>,<span class="dv">7</span>),<span class="kw">rep</span>(<span class="st">&#39;Group3&#39;</span>,<span class="dv">9</span>) ))</code></pre></div>
<p>We can fit the offset model and obtain the design matrix and estimate of <span class="math inline">\(\hat{\sigma}\)</span> via the following code.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">m &lt;-<span class="st"> </span><span class="kw">lm</span>(y <span class="op">~</span><span class="st"> </span>groups)            <span class="co"># Fit the ANOVA model (offset representation)</span>
<span class="kw">coef</span>(m)                        <span class="co"># Show me beta.hat</span></code></pre></div>
<pre><code>##  (Intercept) groupsGroup2 groupsGroup3 
##     86.75000    -11.17857    -15.75000</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">X &lt;-<span class="st"> </span><span class="kw">model.matrix</span>(m)           <span class="co"># obtains the design matrix</span>
sigma.hat &lt;-<span class="st"> </span><span class="kw">summary</span>(m)<span class="op">$</span>sigma  <span class="co"># create the summary table and grab sigma.hat </span>
beta.hat &lt;-<span class="st"> </span><span class="kw">coef</span>(m)
XtX.inv &lt;-<span class="st"> </span><span class="kw">solve</span>( <span class="kw">t</span>(X) <span class="op">%*%</span><span class="st"> </span>X )</code></pre></div>
<p>Now we calculate</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">contr &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">0</span>)  <span class="co"># define my contrast</span>
ctb &lt;-<span class="st"> </span><span class="kw">t</span>(contr) <span class="op">%*%</span><span class="st"> </span>beta.hat
std.err &lt;-<span class="st"> </span>sigma.hat <span class="op">*</span><span class="st"> </span><span class="kw">sqrt</span>( <span class="kw">t</span>(contr) <span class="op">%*%</span><span class="st"> </span>XtX.inv <span class="op">%*%</span><span class="st"> </span>contr )
ctb</code></pre></div>
<pre><code>##          [,1]
## [1,] 75.57143</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">std.err</code></pre></div>
<pre><code>##          [,1]
## [1,] 1.622994</code></pre>
<p>and notice this is the exact same estimate and standard error we got for group two when we fit the cell means model.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">CellMeansModel &lt;-<span class="st"> </span><span class="kw">lm</span>(y <span class="op">~</span><span class="st"> </span>groups <span class="op">-</span><span class="st"> </span><span class="dv">1</span>)
<span class="kw">summary</span>(CellMeansModel)<span class="op">$</span>coefficients</code></pre></div>
<pre><code>##              Estimate Std. Error  t value     Pr(&gt;|t|)
## groupsGroup1 86.75000   1.518172 57.14108 1.567052e-24
## groupsGroup2 75.57143   1.622994 46.56296 1.117034e-22
## groupsGroup3 71.00000   1.431347 49.60364 2.993023e-23</code></pre>
</div>
<div id="estimating-contrasts-using-glht" class="section level2">
<h2><span class="header-section-number">5.2</span> Estimating contrasts using <code>glht()</code></h2>
<p>Instead of us doing all the matrix calculations ourselves, all we really need is to is specify the row vector <span class="math inline">\(\boldsymbol{c}^{T}\)</span>. The function that will do the rest of the calculations is the generalized linear hypothesis test function <code>glht()</code> that can be found in the multiple comparisons package <code>multcomp</code>. The p-values will be adjusted to correct for testing multiple hypothesis, so there may be slight differences compared to the p-value seen in just the regular summary table.</p>
<div id="way-anova" class="section level3">
<h3><span class="header-section-number">5.2.1</span> 1-way ANOVA</h3>
<p>We will again use the Hostility data set and demonstrate how to calculate the point estimates, standard errors and confidence intervals for the group means given a model fit using the offset representation.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">y &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">96</span>,<span class="dv">79</span>,<span class="dv">91</span>,<span class="dv">85</span>,<span class="dv">83</span>,<span class="dv">91</span>,<span class="dv">82</span>,<span class="dv">87</span>,
       <span class="dv">77</span>,<span class="dv">76</span>,<span class="dv">74</span>,<span class="dv">73</span>,<span class="dv">78</span>,<span class="dv">71</span>,<span class="dv">80</span>,
       <span class="dv">66</span>,<span class="dv">73</span>,<span class="dv">69</span>,<span class="dv">66</span>,<span class="dv">77</span>,<span class="dv">73</span>,<span class="dv">71</span>,<span class="dv">70</span>,<span class="dv">74</span>)
groups &lt;-<span class="st"> </span><span class="kw">factor</span>(<span class="kw">c</span>( <span class="kw">rep</span>(<span class="st">&#39;Group1&#39;</span>,<span class="dv">8</span>), <span class="kw">rep</span>(<span class="st">&#39;Group2&#39;</span>,<span class="dv">7</span>),<span class="kw">rep</span>(<span class="st">&#39;Group3&#39;</span>,<span class="dv">9</span>) ))
m &lt;-<span class="st"> </span><span class="kw">lm</span>(y <span class="op">~</span><span class="st"> </span>groups)
<span class="kw">summary</span>(m)<span class="op">$</span>coefficients</code></pre></div>
<pre><code>##               Estimate Std. Error   t value     Pr(&gt;|t|)
## (Intercept)   86.75000   1.518172 57.141079 1.567052e-24
## groupsGroup2 -11.17857   2.222377 -5.030008 5.583942e-05
## groupsGroup3 -15.75000   2.086528 -7.548424 2.063600e-07</code></pre>
<p>We will now define a row vector (and it needs to be a matrix or else <code>glht()</code> will throw an error. First we note that the simple contrast <span class="math inline">\(\boldsymbol{c}^{T}=\left[1\;0\;0\right]\)</span> just grabs the first coefficient and gives us the same estimate and standard error as the summary did.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(multcomp)
contr &lt;-<span class="st"> </span><span class="kw">rbind</span>(<span class="st">&quot;Intercept&quot;</span>=<span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">0</span>)) <span class="co"># 1x3 matrix with row named &quot;Intercept&quot;</span>
test &lt;-<span class="st"> </span><span class="kw">glht</span>(m, <span class="dt">linfct=</span>contr)        <span class="co"># the linear function to be tested is contr</span>
<span class="kw">summary</span>(test)</code></pre></div>
<pre><code>## 
##   Simultaneous Tests for General Linear Hypotheses
## 
## Fit: lm(formula = y ~ groups)
## 
## Linear Hypotheses:
##                Estimate Std. Error t value Pr(&gt;|t|)    
## Intercept == 0   86.750      1.518   57.14   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## (Adjusted p values reported -- single-step method)</code></pre>
<p>Next we calculate the estimate of all the group means <span class="math inline">\(\mu\)</span>, <span class="math inline">\(\mu+\tau_{2}\)</span> and <span class="math inline">\(\mu+\tau_{3}\)</span> and the difference between group 2 and 3. Notice I can specify more than one contrast at a time.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">contr &lt;-<span class="st"> </span><span class="kw">rbind</span>(<span class="st">&quot;Mean of Group 1&quot;</span>=<span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">0</span>),
               <span class="st">&quot;Mean of Group 2&quot;</span>=<span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">0</span>),
               <span class="st">&quot;Mean of Group 3&quot;</span>=<span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">1</span>),
               <span class="st">&quot;Diff G2-G3&quot;</span>     =<span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="op">-</span><span class="dv">1</span>)) 
test &lt;-<span class="st"> </span><span class="kw">glht</span>(m, <span class="dt">linfct=</span>contr)
<span class="kw">summary</span>(test)</code></pre></div>
<pre><code>## 
##   Simultaneous Tests for General Linear Hypotheses
## 
## Fit: lm(formula = y ~ groups)
## 
## Linear Hypotheses:
##                      Estimate Std. Error t value Pr(&gt;|t|)    
## Mean of Group 1 == 0   86.750      1.518  57.141   &lt;0.001 ***
## Mean of Group 2 == 0   75.571      1.623  46.563   &lt;0.001 ***
## Mean of Group 3 == 0   71.000      1.431  49.604   &lt;0.001 ***
## Diff G2-G3 == 0         4.571      2.164   2.112    0.144    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## (Adjusted p values reported -- single-step method)</code></pre>
<p>Finally we calculate confidence intervals in the usual manner using the <code>confint()</code> function.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">confint</span>(test, <span class="dt">level=</span><span class="fl">0.95</span>)</code></pre></div>
<pre><code>## 
##   Simultaneous Confidence Intervals
## 
## Fit: lm(formula = y ~ groups)
## 
## Quantile = 2.6455
## 95% family-wise confidence level
##  
## 
## Linear Hypotheses:
##                      Estimate lwr     upr    
## Mean of Group 1 == 0 86.7500  82.7337 90.7663
## Mean of Group 2 == 0 75.5714  71.2778 79.8650
## Mean of Group 3 == 0 71.0000  67.2134 74.7866
## Diff G2-G3 == 0       4.5714  -1.1534 10.2962</code></pre>
</div>
<div id="ancova-example" class="section level3">
<h3><span class="header-section-number">5.2.2</span> ANCOVA example</h3>
<p>In the ANCOVA case, there are more interesting contrasts to be made. For this example we will use the <code>ToothGrowth</code> dataset. This data measuring the effects of different dose levels of vitamin C on tooth growth of guinea pigs. The two different delivery methods are encoded by the variable supp which has levels of orange juice (OJ) and ascorbic acid (VC).</p>
<p>We first fit a ANCOVA model with an interaction between log(dose) level and delivery method and graph the result.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">data</span>(<span class="st">&#39;ToothGrowth&#39;</span>)
ToothGrowth<span class="op">$</span>logDose &lt;-<span class="st"> </span><span class="kw">log</span>( ToothGrowth<span class="op">$</span>dose )
m &lt;-<span class="st"> </span><span class="kw">lm</span>(len <span class="op">~</span><span class="st"> </span>logDose <span class="op">*</span><span class="st"> </span>supp, <span class="dt">data=</span>ToothGrowth)

<span class="co"># predict() gives me the yhat values and optional CI</span>
<span class="co"># these are just the &quot;contrasts&quot; defined by X matrix! </span>
ToothGrowth &lt;-<span class="st"> </span>ToothGrowth <span class="op">%&gt;%</span>
<span class="st">  </span>dplyr<span class="op">::</span><span class="kw">do</span>(<span class="cf">if</span>(<span class="op">!</span><span class="kw">is.null</span>(.<span class="op">$</span>fit)){dplyr<span class="op">::</span><span class="kw">select</span>(<span class="op">-</span>fit,<span class="op">-</span>upr,<span class="op">-</span>lwr )}<span class="cf">else</span>{.}) <span class="op">%&gt;%</span><span class="st">   </span>
<span class="st">  </span><span class="kw">cbind</span>( <span class="kw">predict</span>(m, <span class="dt">interval=</span><span class="st">&#39;confidence&#39;</span>))

<span class="co"># Plot the results using ggplot2</span>
<span class="kw">ggplot</span>( ToothGrowth, <span class="kw">aes</span>(<span class="dt">x=</span>logDose, <span class="dt">col=</span>supp, <span class="dt">fill=</span>supp)) <span class="op">+</span>
<span class="st">    </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">y=</span>len)) <span class="op">+</span>
<span class="st">    </span><span class="kw">geom_line</span>(<span class="kw">aes</span>(<span class="dt">y=</span>fit)) <span class="op">+</span>
<span class="st">    </span><span class="kw">geom_ribbon</span>(<span class="kw">aes</span>(<span class="dt">ymin=</span>lwr, <span class="dt">ymax=</span>upr), <span class="dt">alpha=</span>.<span class="dv">2</span>)</code></pre></div>
<p><img src="Statistical_Methods_II_files/figure-html/unnamed-chunk-69-1.png" width="672" /></p>
<p>R has fit this model using the offset representation. First we present the summary coefficients so we know which parameters are which.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(m)<span class="op">$</span>coefficient</code></pre></div>
<pre><code>##                 Estimate Std. Error   t value     Pr(&gt;|t|)
## (Intercept)    20.663333  0.6791481 30.425371 1.629404e-36
## logDose         9.254889  1.2000095  7.712346 2.302639e-10
## suppVC         -3.700000  0.9604605 -3.852319 3.033467e-04
## logDose:suppVC  3.844782  1.6970696  2.265542 2.736578e-02</code></pre>
<p>For a warm-up, we will calculate the y-intercepts of both groups and the slopes of both. For the OJ group, this is just the 1st and 2nd coefficients, while for the VC group it is <span class="math inline">\(\beta_{0}+\beta_{2}\)</span> and <span class="math inline">\(\beta_{1}+\beta_{3}\)</span>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Add a heading so that I know which parameter is which!</span>
<span class="co">#                                Int  logDose  suppVC   logDose:suppVC</span>
contr &lt;-<span class="st"> </span><span class="kw">rbind</span>(<span class="st">&quot;Intercept OJ&quot;</span> =<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>,     <span class="dv">0</span>,     <span class="dv">0</span>,          <span class="dv">0</span>          ),
               <span class="st">&quot;Slope     OJ&quot;</span> =<span class="st"> </span><span class="kw">c</span>(<span class="dv">0</span>,     <span class="dv">1</span>,     <span class="dv">0</span>,          <span class="dv">0</span>          ),
               <span class="st">&quot;Intercept VC&quot;</span> =<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>,     <span class="dv">0</span>,     <span class="dv">1</span>,          <span class="dv">0</span>          ),
               <span class="st">&quot;Slope     VC&quot;</span> =<span class="st"> </span><span class="kw">c</span>(<span class="dv">0</span>,     <span class="dv">1</span>,     <span class="dv">0</span>,          <span class="dv">1</span>          ) ) 
test &lt;-<span class="st"> </span><span class="kw">glht</span>(m, <span class="dt">linfct=</span>contr)
<span class="kw">summary</span>(test)</code></pre></div>
<pre><code>## 
##   Simultaneous Tests for General Linear Hypotheses
## 
## Fit: lm(formula = len ~ logDose * supp, data = ToothGrowth)
## 
## Linear Hypotheses:
##                   Estimate Std. Error t value Pr(&gt;|t|)    
## Intercept OJ == 0  20.6633     0.6791  30.425  &lt; 1e-10 ***
## Slope     OJ == 0   9.2549     1.2000   7.712 3.18e-10 ***
## Intercept VC == 0  16.9633     0.6791  24.977  &lt; 1e-10 ***
## Slope     VC == 0  13.0997     1.2000  10.916  &lt; 1e-10 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## (Adjusted p values reported -- single-step method)</code></pre>
<p>In our original table of summary coefficients, the (intercept) term corresponds to the tooth growth of a guinea pig when the logDose level is 0 (and therefore dose=1). If I wanted to estimate the tooth growth of a guinea pig fed OJ but with only <span class="math inline">\(1/2\)</span> a dose (and therefore <span class="math inline">\(logDose=\log\left(1/2\right)=-0.69\)</span>), then we want</p>
<p><span class="math display">\[\begin{aligned}
\hat{y}_{oj,dose=0.5}   &amp; =     \hat{\beta}_{0}+\hat{\beta}_{1}\log\left(0.5\right)\\
                        &amp; =     20.6+9.25\log\left(0.5\right)\\
                        &amp; =     20.6+9.25\left(-0.69\right)\\
                        &amp; =     14.21
\end{aligned}\]</span></p>
<p>which I can write as <span class="math display">\[y_{oj,dose=0.5}   =   \left[\begin{array}{cccc}
1 &amp; -0.69 &amp; 0 &amp; 0\end{array}\right]\left[\begin{array}{c}
\hat{\beta_{0}}\\
\hat{\beta}_{1}\\
\hat{\beta}_{2}\\
\hat{\beta}_{3}
\end{array}\right]
    =   \boldsymbol{c}_{1}^{T}\hat{\boldsymbol{\beta}}\]</span></p>
<p>To calculate the same value for the VC group, we need the following contrast:</p>
<p><span class="math display">\[\begin{aligned}
\hat{y}_{vc,dose=0.5}   
    &amp;=  16.9633+13.0997\,\log\left(0.5\right)\\
    &amp;=  \left(20.66-3.7\right)+\left(9.25+3.8\right)\,\log\left(0.5\right)\\
      &amp;=    \left(\hat{\beta}_{0}+\hat{\beta}_{2}\right)+\left(\hat{\beta}_{1}+\hat{\beta}_{3}\right)\,\left(-0.69\right)\\
      &amp;=    \left[\begin{array}{cccc}1 &amp; -0.69 &amp; 1 &amp; -0.69\end{array}\right]\left[\begin{array}{c}
                 \hat{\beta_{0}}\\
                 \hat{\beta}_{1}\\
                 \hat{\beta}_{2}\\
                 \hat{\beta}_{3}\end{array}\right]\\
      &amp;=    \boldsymbol{c}_{2}^{T}\hat{\boldsymbol{\beta}}
      \end{aligned}\]</span></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#                                Int  logDose  suppVC   logDose:suppVC</span>
contr &lt;-<span class="st"> </span><span class="kw">rbind</span>(<span class="st">&quot;OJ; 1/2 dose&quot;</span> =<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>,   <span class="op">-</span><span class="fl">0.69</span>,    <span class="dv">0</span>,          <span class="dv">0</span>         ),
               <span class="st">&quot;VC; 1/2 dose&quot;</span> =<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>,   <span class="op">-</span><span class="fl">0.69</span>,    <span class="dv">1</span>,        <span class="op">-</span><span class="fl">0.69</span>       ))
test &lt;-<span class="st"> </span><span class="kw">glht</span>(m, <span class="dt">linfct=</span>contr)
<span class="kw">summary</span>(test)</code></pre></div>
<pre><code>## 
##   Simultaneous Tests for General Linear Hypotheses
## 
## Fit: lm(formula = len ~ logDose * supp, data = ToothGrowth)
## 
## Linear Hypotheses:
##                   Estimate Std. Error t value Pr(&gt;|t|)    
## OJ; 1/2 dose == 0   14.277      1.071   13.33  &lt; 1e-10 ***
## VC; 1/2 dose == 0    7.925      1.071    7.40 1.51e-09 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## (Adjusted p values reported -- single-step method)</code></pre>
<p>Finally we might be interested in testing if there is a treatment difference between OJ and VC at a 1/2 dose level. So to do this, we want to calculate the difference between these two previous contrasts, i.e.</p>
<p><span class="math display">\[\begin{aligned}
\boldsymbol{c}_{1}^{T}\hat{\boldsymbol{\beta}}-\boldsymbol{c}_{2}^{T}\hat{\boldsymbol{\beta}}   &amp;=  \left(\boldsymbol{c}_{1}^{T}-\boldsymbol{c}_{2}^{T}\right) \hat{\boldsymbol{ \beta }} \\
    &amp;=  \left(\left[\begin{array}{cccc}
1 &amp; -0.69 &amp; 0 &amp; 0\end{array}\right]-\left[\begin{array}{cccc}
1 &amp; -0.69 &amp; 1 &amp; -0.69\end{array}\right]\right)\hat{\boldsymbol{\beta}} \\
    &amp;=  \left[\begin{array}{cccc}
0 &amp; 0 &amp; -1 &amp; 0.69\end{array}\right]\hat{\boldsymbol{\beta}}
\end{aligned}\]</span></p>
<p>and we can calculate</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">contr &lt;-<span class="st"> </span><span class="kw">rbind</span>(<span class="st">&quot;OJ - VC; 1/2 dose&quot;</span> =<span class="st"> </span><span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="op">-</span><span class="dv">1</span>, <span class="fl">0.69</span>))
test &lt;-<span class="st"> </span><span class="kw">glht</span>(m, <span class="dt">linfct=</span>contr)
<span class="kw">summary</span>(test)</code></pre></div>
<pre><code>## 
##   Simultaneous Tests for General Linear Hypotheses
## 
## Fit: lm(formula = len ~ logDose * supp, data = ToothGrowth)
## 
## Linear Hypotheses:
##                        Estimate Std. Error t value Pr(&gt;|t|)    
## OJ - VC; 1/2 dose == 0    6.353      1.514   4.195 9.83e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## (Adjusted p values reported -- single-step method)</code></pre>
<p>When we do the same test, but at dose level 2 (logDose =<span class="math inline">\(\log2=0.69\)</span>) we see that the difference is not statistically significant.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">contr &lt;-<span class="st"> </span><span class="kw">rbind</span>(<span class="st">&quot;OJ - VC; dose 2&quot;</span> =<span class="st"> </span><span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="op">-</span><span class="dv">1</span>, <span class="op">-</span><span class="fl">0.69</span>))
test &lt;-<span class="st"> </span><span class="kw">glht</span>(m, <span class="dt">linfct=</span>contr)
<span class="kw">summary</span>(test)</code></pre></div>
<pre><code>## 
##   Simultaneous Tests for General Linear Hypotheses
## 
## Fit: lm(formula = len ~ logDose * supp, data = ToothGrowth)
## 
## Linear Hypotheses:
##                      Estimate Std. Error t value Pr(&gt;|t|)
## OJ - VC; dose 2 == 0    1.047      1.514   0.691    0.492
## (Adjusted p values reported -- single-step method)</code></pre>
</div>
</div>
<div id="using-emmeans-package" class="section level2">
<h2><span class="header-section-number">5.3</span> Using <code>emmeans</code> Package</h2>
<p>Specifying the contrasts by hand is extremely difficult to do correctly and instead we would prefer to specify the contrasts using language like “create all possible pairwise contrasts” where each pair is just a subtraction. The R-package <code>emmeans</code> tries to simply the creation of common contrasts.</p>
<p>To show how to use the <code>emmeans</code> package, we’ll consider a bunch of common models and show how to address common statistical questions for each.</p>
<div id="simple-regression-1" class="section level3">
<h3><span class="header-section-number">5.3.1</span> Simple Regression</h3>
<p>There is a dataset built into R named <code>trees</code> which describes a set of <span class="math inline">\(n=31\)</span> cherry trees and the goal is to predict the volume of timber produced by each tree just using the tree girth a 4.5 feet above the ground.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">data</span>(trees)
model &lt;-<span class="st"> </span><span class="kw">lm</span>( Volume <span class="op">~</span><span class="st"> </span>Girth, <span class="dt">data=</span>trees )
trees &lt;-<span class="st"> </span>trees <span class="op">%&gt;%</span>
<span class="st">  </span>dplyr<span class="op">::</span><span class="kw">do</span>(<span class="cf">if</span>(<span class="op">!</span><span class="kw">is.null</span>(.<span class="op">$</span>fit)){dplyr<span class="op">::</span><span class="kw">select</span>(<span class="op">-</span>fit,<span class="op">-</span>upr,<span class="op">-</span>lwr )}<span class="cf">else</span>{.}) <span class="op">%&gt;%</span><span class="st">   </span>
<span class="st">  </span><span class="kw">cbind</span>( <span class="kw">predict</span>(model, <span class="dt">interval=</span><span class="st">&#39;conf&#39;</span>))
<span class="kw">ggplot</span>(trees, <span class="kw">aes</span>(<span class="dt">x=</span>Girth, <span class="dt">y=</span>Volume)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_ribbon</span>( <span class="kw">aes</span>(<span class="dt">ymin=</span>lwr, <span class="dt">ymax=</span>upr), <span class="dt">alpha=</span>.<span class="dv">3</span> ) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_line</span>( <span class="kw">aes</span>(<span class="dt">y=</span>fit) )</code></pre></div>
<p><img src="Statistical_Methods_II_files/figure-html/unnamed-chunk-75-1.png" width="672" /></p>
<p>Using the <code>summary()</code> function, we can test hypotheses about if the y-intercept or slope could be equal to zero, but we might be interested in confidence intervals for the regression line at girth values of 10 and 12.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># We could find the regression line heights and CI using </span>
<span class="co"># either predict() or emmeans()</span>
<span class="kw">predict</span>(model, <span class="dt">newdata=</span><span class="kw">data.frame</span>(<span class="dt">Girth=</span><span class="kw">c</span>(<span class="dv">10</span>,<span class="dv">12</span>)), <span class="dt">interval=</span><span class="st">&#39;conf&#39;</span> )</code></pre></div>
<pre><code>##        fit      lwr      upr
## 1 13.71511 11.44781 15.98240
## 2 23.84682 22.16204 25.53159</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">emmeans</span>(model, <span class="dt">specs =</span> <span class="op">~</span>Girth, <span class="dt">at=</span><span class="kw">list</span>(<span class="dt">Girth=</span><span class="kw">c</span>(<span class="dv">10</span>,<span class="dv">12</span>)) )  </code></pre></div>
<pre><code>##  Girth   emmean        SE df lower.CL upper.CL
##     10 13.71511 1.1085761 29 11.44781 15.98240
##     12 23.84682 0.8237582 29 22.16204 25.53159
## 
## Confidence level used: 0.95</code></pre>
<p>The <code>emmeans()</code> function requires us to specify the grid of reference points we are interested as well as which variable or variables we wish to separate out. In the simple regression case, the <code>specs</code> argument is just the single covariate.</p>
<p>We might next ask if the difference in volume between a tree with 10 inch girth is statistically different than a tree with 12 inch girth? In other words, we want to test <span class="math display">\[ H_0:\; (\beta_0 + \beta_1\cdot10 ) - (\beta_0 + \beta_1 \cdot 12) = 0\]</span> <span class="math display">\[ H_a:\; (\beta_0 + \beta_1\cdot10 ) - (\beta_0 + \beta_1 \cdot 12) \ne 0\]</span></p>
<p>In this case, we want to look at all possible pairwise differences between the predicted values at <span class="math inline">\(10\)</span> and <span class="math inline">\(12\)</span>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">emmeans</span>(model, <span class="dt">specs =</span> pairwise<span class="op">~</span>Girth,
        <span class="dt">at=</span><span class="kw">list</span>(<span class="dt">Girth=</span><span class="kw">c</span>(<span class="dv">10</span>,<span class="dv">12</span>)) ) </code></pre></div>
<pre><code>## $emmeans
##  Girth   emmean        SE df lower.CL upper.CL
##     10 13.71511 1.1085761 29 11.44781 15.98240
##     12 23.84682 0.8237582 29 22.16204 25.53159
## 
## Confidence level used: 0.95 
## 
## $contrasts
##  contrast  estimate        SE df t.ratio p.value
##  10 - 12  -10.13171 0.4947539 29 -20.478  &lt;.0001</code></pre>
<p>Notice that if I was interested in 3 points, we would get all of the differences.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">emmeans</span>(model, <span class="dt">specs =</span> pairwise<span class="op">~</span>Girth,
        <span class="dt">at=</span><span class="kw">list</span>(<span class="dt">Girth=</span><span class="kw">c</span>(<span class="dv">10</span>,<span class="dv">11</span>,<span class="dv">12</span>)) ) </code></pre></div>
<pre><code>## $emmeans
##  Girth   emmean        SE df lower.CL upper.CL
##     10 13.71511 1.1085761 29 11.44781 15.98240
##     11 18.78096 0.9447560 29 16.84872 20.71320
##     12 23.84682 0.8237582 29 22.16204 25.53159
## 
## Confidence level used: 0.95 
## 
## $contrasts
##  contrast   estimate        SE df t.ratio p.value
##  10 - 11   -5.065856 0.2473770 29 -20.478  &lt;.0001
##  10 - 12  -10.131713 0.4947539 29 -20.478  &lt;.0001
##  11 - 12   -5.065856 0.2473770 29 -20.478  &lt;.0001
## 
## P value adjustment: tukey method for comparing a family of 3 estimates</code></pre>
<p>In this very simple case, the slope parameter is easily available as a parameter value, but we could use the <code>emtrends()</code> function to obtain the slope.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">emtrends</span>( model, <span class="op">~</span>Girth, <span class="st">&#39;Girth&#39;</span> )</code></pre></div>
<pre><code>##     Girth Girth.trend       SE df lower.CL upper.CL
##  13.24839    5.065856 0.247377 29 4.559914 5.571799
## 
## Confidence level used: 0.95</code></pre>
<p>This output is a bit mysterious because because of the <code>13.248</code> component. What has happened is that <code>emtrends</code> is telling us the slope of the line at a particular point on the x-axis (the mean of all the girth values). While this doesn’t matter in this example, because the slope is the same for all values of girth, if we had fit a quadratic model, it would not.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">model &lt;-<span class="st"> </span><span class="kw">lm</span>( Volume <span class="op">~</span><span class="st"> </span><span class="kw">poly</span>(Girth, <span class="dv">2</span>), <span class="dt">data=</span>trees )      <span class="co"># Girth + Girth^2</span>
trees &lt;-<span class="st"> </span>trees <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span>dplyr<span class="op">::</span><span class="kw">select</span>(Volume, Girth) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">cbind</span>(<span class="kw">predict</span>(model, <span class="dt">interval=</span><span class="st">&#39;conf&#39;</span>))

<span class="kw">ggplot</span>(trees, <span class="kw">aes</span>(<span class="dt">x=</span>Girth, <span class="dt">y=</span>Volume)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_ribbon</span>( <span class="kw">aes</span>(<span class="dt">ymin=</span>lwr, <span class="dt">ymax=</span>upr), <span class="dt">alpha=</span>.<span class="dv">3</span> ) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_line</span>( <span class="kw">aes</span>(<span class="dt">y=</span>fit) )</code></pre></div>
<p><img src="Statistical_Methods_II_files/figure-html/unnamed-chunk-80-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">emtrends</span>( model, <span class="op">~</span><span class="st"> </span><span class="kw">poly</span>(Girth,<span class="dv">2</span>), <span class="st">&#39;Girth&#39;</span>,
          <span class="dt">at=</span><span class="kw">list</span>(<span class="dt">Girth=</span><span class="kw">c</span>(<span class="dv">10</span>,<span class="dv">11</span>,<span class="dv">12</span>)) )</code></pre></div>
<pre><code>##  Girth Girth.trend        SE df lower.CL upper.CL
##     10    3.029920 0.5041192 28 1.997278 4.062561
##     11    3.538995 0.3992560 28 2.721156 4.356834
##     12    4.048070 0.3028961 28 3.427616 4.668525
## 
## Confidence level used: 0.95</code></pre>
</div>
<div id="way-anova-1" class="section level3">
<h3><span class="header-section-number">5.3.2</span> 1-way ANOVA</h3>
<p>To consider the pairwise contrasts between different levels we will consider the college student hostility data again. A clinical psychologist wished to compare three methods for reducing hostility levels in university students, and used a certain test (HLT) to measure the degree of hostility. A high score on the test indicated great hostility. The psychologist used <span class="math inline">\(24\)</span> students who obtained high and nearly equal scores in the experiment. Eight subjects were selected at random from among the <span class="math inline">\(24\)</span> problem cases and were treated with method 1, seven of the remaining <span class="math inline">\(16\)</span> students were selected at random and treated with method 2 while the remaining nine students were treated with method 3. All treatments were continued for a one-semester period. Each student was given the HLT test at the end of the semester, with the results show in the following table.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">Hostility &lt;-<span class="st"> </span><span class="kw">data.frame</span>(
  <span class="dt">HLT =</span> <span class="kw">c</span>(<span class="dv">96</span>,<span class="dv">79</span>,<span class="dv">91</span>,<span class="dv">85</span>,<span class="dv">83</span>,<span class="dv">91</span>,<span class="dv">82</span>,<span class="dv">87</span>,
          <span class="dv">77</span>,<span class="dv">76</span>,<span class="dv">74</span>,<span class="dv">73</span>,<span class="dv">78</span>,<span class="dv">71</span>,<span class="dv">80</span>,
          <span class="dv">66</span>,<span class="dv">73</span>,<span class="dv">69</span>,<span class="dv">66</span>,<span class="dv">77</span>,<span class="dv">73</span>,<span class="dv">71</span>,<span class="dv">70</span>,<span class="dv">74</span>),
  <span class="dt">Method =</span> <span class="kw">c</span>( <span class="kw">rep</span>(<span class="st">&#39;M1&#39;</span>,<span class="dv">8</span>), <span class="kw">rep</span>(<span class="st">&#39;M2&#39;</span>,<span class="dv">7</span>), <span class="kw">rep</span>(<span class="st">&#39;M3&#39;</span>,<span class="dv">9</span>) ) )</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(Hostility, <span class="kw">aes</span>(<span class="dt">x=</span>Method, <span class="dt">y=</span>HLT)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_boxplot</span>()</code></pre></div>
<p><img src="Statistical_Methods_II_files/figure-html/unnamed-chunk-82-1.png" width="672" /></p>
<p>To use the <code>emmeans()</code>, we again will use the pairwise command where we specify that we want all the pairwise contrasts between Method levels.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">model &lt;-<span class="st"> </span><span class="kw">lm</span>( HLT <span class="op">~</span><span class="st"> </span>Method, <span class="dt">data=</span>Hostility )
<span class="kw">emmeans</span>(model, pairwise<span class="op">~</span>Method)</code></pre></div>
<pre><code>## $emmeans
##  Method   emmean       SE df lower.CL upper.CL
##  M1     86.75000 1.518172 21 83.59279 89.90721
##  M2     75.57143 1.622994 21 72.19623 78.94663
##  M3     71.00000 1.431347 21 68.02335 73.97665
## 
## Confidence level used: 0.95 
## 
## $contrasts
##  contrast  estimate       SE df t.ratio p.value
##  M1 - M2  11.178571 2.222377 21   5.030  0.0002
##  M1 - M3  15.750000 2.086528 21   7.548  &lt;.0001
##  M2 - M3   4.571429 2.163993 21   2.112  0.1114
## 
## P value adjustment: tukey method for comparing a family of 3 estimates</code></pre>
</div>
<div id="ancova" class="section level3">
<h3><span class="header-section-number">5.3.3</span> ANCOVA</h3>
<p>We will return to the <code>ToothGrowth</code> dataset and calculate all the interesting contrasts we previously built by hand.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">data</span>(<span class="st">&#39;ToothGrowth&#39;</span>)
ToothGrowth<span class="op">$</span>logDose &lt;-<span class="st"> </span><span class="kw">log</span>( ToothGrowth<span class="op">$</span>dose )
m &lt;-<span class="st"> </span><span class="kw">lm</span>(len <span class="op">~</span><span class="st"> </span>logDose <span class="op">*</span><span class="st"> </span>supp, <span class="dt">data=</span>ToothGrowth)
ToothGrowth &lt;-<span class="st"> </span>ToothGrowth <span class="op">%&gt;%</span>
<span class="st">  </span>dplyr<span class="op">::</span><span class="kw">do</span>(<span class="cf">if</span>(<span class="op">!</span><span class="kw">is.null</span>(.<span class="op">$</span>fit)){dplyr<span class="op">::</span><span class="kw">select</span>(<span class="op">-</span>fit,<span class="op">-</span>upr,<span class="op">-</span>lwr )}<span class="cf">else</span>{.}) <span class="op">%&gt;%</span><span class="st">   </span>
<span class="st">  </span><span class="kw">cbind</span>( <span class="kw">predict</span>(m, <span class="dt">interval=</span><span class="st">&#39;conf&#39;</span>) )
<span class="kw">ggplot</span>(ToothGrowth, <span class="kw">aes</span>(<span class="dt">x=</span>logDose, <span class="dt">color=</span>supp, <span class="dt">fill=</span>supp)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_ribbon</span>( <span class="kw">aes</span>(<span class="dt">ymin=</span>lwr, <span class="dt">ymax=</span>upr), <span class="dt">alpha=</span>.<span class="dv">3</span> ) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_line</span>( <span class="kw">aes</span>(<span class="dt">y=</span>fit) ) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>( <span class="kw">aes</span>(<span class="dt">y=</span>len) )</code></pre></div>
<p><img src="Statistical_Methods_II_files/figure-html/unnamed-chunk-84-1.png" width="672" /></p>
<p>First, lets get the y-intercept for each group. In the following code, the formula with the <code>| supp</code> part says that we want to do all the calculations for each level of the supplement types. The call to <code>emmeans()</code> calculates the response at logDose level 0. By passing the result of the <code>emmeans()</code> function call to the <code>summary()</code> function, we can tell the summary function to print out both the confidence intervals and t-tests.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">emmeans</span>(m, <span class="op">~</span>logDose <span class="op">|</span><span class="st"> </span>supp, <span class="dt">at=</span><span class="kw">list</span>(<span class="dt">logDose=</span><span class="dv">0</span>)) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">summary</span>(<span class="dt">infer=</span><span class="kw">c</span>(<span class="ot">TRUE</span>,<span class="ot">TRUE</span>))</code></pre></div>
<pre><code>## supp = OJ:
##  logDose   emmean        SE df lower.CL upper.CL t.ratio p.value
##        0 20.66333 0.6791481 56 19.30284 22.02383  30.425  &lt;.0001
## 
## supp = VC:
##  logDose   emmean        SE df lower.CL upper.CL t.ratio p.value
##        0 16.96333 0.6791481 56 15.60284 18.32383  24.977  &lt;.0001
## 
## Confidence level used: 0.95</code></pre>
<p>Next we estimated the tooth growth for a guinea pig with a logdose = -.69 (i.e. dose=1/2) for both the OJ and VC supplements. We also wanted to calculate the contrast between the two supplement predictions.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">emmeans</span>(m, pairwise<span class="op">~</span>logDose<span class="op">*</span>supp, <span class="dt">at=</span><span class="kw">list</span>(<span class="dt">logDose=</span><span class="op">-</span>.<span class="dv">69</span>)) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">summary</span>(<span class="dt">infer=</span><span class="kw">c</span>(<span class="ot">TRUE</span>,<span class="ot">TRUE</span>))</code></pre></div>
<pre><code>## $emmeans
##  logDose supp   emmean       SE df lower.CL upper.CL t.ratio p.value
##    -0.69 OJ   14.27746 1.070905 56 12.13218 16.42274  13.332  &lt;.0001
##    -0.69 VC    7.92456 1.070905 56  5.77928 10.06984   7.400  &lt;.0001
## 
## Confidence level used: 0.95 
## 
## $contrasts
##  contrast            estimate       SE df lower.CL upper.CL t.ratio
##  -0.69,OJ - -0.69,VC   6.3529 1.514488 56 3.319016 9.386784   4.195
##  p.value
##   0.0001
## 
## Confidence level used: 0.95</code></pre>
<p>We next make the same comparison for logdose = 0.69 (i.e. dose=2).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">emmeans</span>(m, pairwise<span class="op">~</span>logDose<span class="op">*</span>supp, <span class="dt">at=</span><span class="kw">list</span>(<span class="dt">logDose=</span>.<span class="dv">69</span>)) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">summary</span>(<span class="dt">infer=</span><span class="kw">c</span>(<span class="ot">TRUE</span>,<span class="ot">TRUE</span>))</code></pre></div>
<pre><code>## $emmeans
##  logDose supp   emmean       SE df lower.CL upper.CL t.ratio p.value
##     0.69 OJ   27.04921 1.070905 56 24.90393 29.19449  25.258  &lt;.0001
##     0.69 VC   26.00211 1.070905 56 23.85683 28.14739  24.281  &lt;.0001
## 
## Confidence level used: 0.95 
## 
## $contrasts
##  contrast          estimate       SE df  lower.CL upper.CL t.ratio p.value
##  0.69,OJ - 0.69,VC   1.0471 1.514488 56 -1.986784 4.080984   0.691  0.4922
## 
## Confidence level used: 0.95</code></pre>
<p>While <code>emmeans()</code> makes it very easy to calculate the <span class="math inline">\(\hat{y}\)</span> value for some covariate combination or some difference of <span class="math inline">\(\hat{y}\)</span> values, it doesn’t handle slope parameters particularly well. The companion function <code>emtrends()</code> is intended to make similar calculations among slopes easy to create. We will now assess the difference in slopes between the two groups.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">emtrends</span>(m, <span class="op">~</span>logDose<span class="op">*</span>supp, <span class="dt">var =</span> <span class="st">&#39;logDose&#39;</span>)</code></pre></div>
<pre><code>##  logDose supp logDose.trend       SE df  lower.CL upper.CL
##        0 OJ        9.254889 1.200009 56  6.850981 11.65880
##        0 VC       13.099671 1.200009 56 10.695763 15.50358
## 
## Confidence level used: 0.95</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">emtrends</span>(m, pairwise<span class="op">~</span>logDose<span class="op">*</span>supp, <span class="dt">var =</span> <span class="st">&#39;logDose&#39;</span>)</code></pre></div>
<pre><code>## $emtrends
##  logDose supp logDose.trend       SE df  lower.CL upper.CL
##        0 OJ        9.254889 1.200009 56  6.850981 11.65880
##        0 VC       13.099671 1.200009 56 10.695763 15.50358
## 
## Confidence level used: 0.95 
## 
## $contrasts
##  contrast     estimate      SE df t.ratio p.value
##  0,OJ - 0,VC -3.844782 1.69707 56  -2.266  0.0274</code></pre>
<div id="common-emmeans-mistake" class="section level4">
<h4><span class="header-section-number">5.3.3.1</span> Common <code>emmeans()</code> mistake</h4>
<p>It is very common to make a mistake using <code>emmeans()</code> or <code>emtrends()</code> if you don’t understand what the specification formula means. In particular what happens if you were to use <code>~logDose</code> instead of the correct <code>~logDose*supp</code>.</p>
<p>Consider the case where we are interested in making predictions for each supplement type at <span class="math inline">\(1/2\)</span> dose (logDose=-0.69).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">emmeans</span>(m, <span class="op">~</span>logDose<span class="op">*</span>supp, <span class="dt">at=</span><span class="kw">list</span>(<span class="dt">logDose=</span><span class="op">-</span>.<span class="dv">69</span>))</code></pre></div>
<pre><code>##  logDose supp   emmean       SE df lower.CL upper.CL
##    -0.69 OJ   14.27746 1.070905 56 12.13218 16.42274
##    -0.69 VC    7.92456 1.070905 56  5.77928 10.06984
## 
## Confidence level used: 0.95</code></pre>
<p>If I were to accidentally forget the <code>supp</code> part of this, then <code>emmeans()</code> would figure that I wanted to <em>average</em> over the two levels and give me the average of <span class="math inline">\(14.28\)</span> and <span class="math inline">\(7.92\)</span>, which is <span class="math inline">\(11.1\)</span>. With the interaction term in the model, it is unlikely that I would want to do this, but <code>emmeans()</code> complains a little but lets me do it.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">emmeans</span>(m, <span class="op">~</span>logDose, <span class="dt">at=</span><span class="kw">list</span>(<span class="dt">logDose=</span><span class="op">-</span>.<span class="dv">69</span>))</code></pre></div>
<pre><code>## NOTE: Results may be misleading due to involvement in interactions</code></pre>
<pre><code>##  logDose   emmean       SE df lower.CL upper.CL
##    -0.69 11.10101 0.757244 56 9.584068 12.61795
## 
## Results are averaged over the levels of: supp 
## Confidence level used: 0.95</code></pre>
<p>What would happen if we only use <code>supp</code> in the formula specification? In this case we are lucky because the <code>logDose=-0.69</code> specified what dose level to look at. If we had forgotten to specify this, then we would have done this calculation at the mean <code>logDose</code> value, which happens to be zero.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">emmeans</span>(m, <span class="op">~</span>supp<span class="op">*</span>logDose, <span class="dt">at=</span><span class="kw">list</span>(<span class="dt">logDose=</span><span class="dv">0</span>))</code></pre></div>
<pre><code>##  supp logDose   emmean        SE df lower.CL upper.CL
##  OJ         0 20.66333 0.6791481 56 19.30284 22.02383
##  VC         0 16.96333 0.6791481 56 15.60284 18.32383
## 
## Confidence level used: 0.95</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">emmeans</span>(m, <span class="op">~</span>supp)</code></pre></div>
<pre><code>## NOTE: Results may be misleading due to involvement in interactions</code></pre>
<pre><code>##  supp   emmean        SE df lower.CL upper.CL
##  OJ   20.66333 0.6791481 56 19.30284 22.02383
##  VC   16.96333 0.6791481 56 15.60284 18.32383
## 
## Confidence level used: 0.95</code></pre>
<p>Because the averaging over factor levels isn’t what I typically want to do, I start the analysis making sure the model formula I used in the <code>lm()</code> command is the same as the one I pass into <code>emmeans()</code>.</p>
</div>
</div>
</div>
<div id="exercises-4" class="section level2">
<h2><span class="header-section-number">5.4</span> Exercises</h2>
<ol style="list-style-type: decimal">
<li><p>We will examine a dataset that summarizes cars featured in the magazine Motor Trend during the year 1974. In particular we will examine the relationship between the vehicles gas mileage (<code>mpg</code>) versus the weight (<code>wt</code>) and number of cylinders (<code>cyl</code>) of the vehicle.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(ggplot2)
<span class="kw">library</span>(dplyr)
<span class="kw">data</span>(mtcars)
mtcars<span class="op">$</span>cyl &lt;-<span class="st"> </span><span class="kw">factor</span>(mtcars<span class="op">$</span>cyl)     <span class="co"># treat cylinders as categorical</span>
<span class="kw">ggplot</span>(mtcars, <span class="kw">aes</span>(<span class="dt">x=</span>wt, <span class="dt">col=</span>cyl)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">y=</span>mpg, <span class="dt">shape=</span>cyl), <span class="dt">size=</span><span class="dv">4</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">xlab</span>(<span class="st">&#39;Weight (tons)&#39;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">ylab</span>(<span class="st">&#39;Miles per Gallon&#39;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">color=</span><span class="st">&#39;Cylinders&#39;</span>, <span class="dt">shape=</span><span class="st">&#39;Cylinders&#39;</span>)</code></pre></div>
<img src="Statistical_Methods_II_files/figure-html/unnamed-chunk-92-1.png" width="672" />
<ol style="list-style-type: lower-alpha">
<li><p>Create a smaller set of data with just 9 observations (3 from each cylinder group) and create the design matrix <span class="math inline">\(\boldsymbol{X}\)</span> for fitting the the model for estimating mpg using both weight and number of cylinders and their interaction using the following code:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mtcars <span class="op">%&gt;%</span><span class="st">      </span>
<span class="st">  </span><span class="kw">group_by</span>(cyl) <span class="op">%&gt;%</span><span class="st">              </span><span class="co"># For each cylinder group</span>
<span class="st">  </span><span class="kw">arrange</span>(cyl, wt) <span class="op">%&gt;%</span><span class="st">           </span><span class="co"># Reorder my dataset</span>
<span class="st">  </span><span class="kw">slice</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">3</span>)  <span class="op">%&gt;%</span><span class="st">                </span><span class="co"># grab first three rows of each group</span>
<span class="st">  </span><span class="kw">lm</span>( mpg <span class="op">~</span><span class="st"> </span>wt<span class="op">*</span>cyl, <span class="dt">data=</span>. ) <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># Linear model</span>
<span class="st">  </span><span class="kw">model.matrix</span>()</code></pre></div>
<pre><code>##   (Intercept)    wt cyl6 cyl8 wt:cyl6 wt:cyl8
## 1           1 1.513    0    0   0.000   0.000
## 2           1 1.615    0    0   0.000   0.000
## 3           1 1.835    0    0   0.000   0.000
## 4           1 2.620    1    0   2.620   0.000
## 5           1 2.770    1    0   2.770   0.000
## 6           1 2.875    1    0   2.875   0.000
## 7           1 3.170    0    1   0.000   3.170
## 8           1 3.435    0    1   0.000   3.435
## 9           1 3.440    0    1   0.000   3.440
## attr(,&quot;assign&quot;)
## [1] 0 1 2 2 3 3
## attr(,&quot;contrasts&quot;)
## attr(,&quot;contrasts&quot;)$cyl
## [1] &quot;contr.treatment&quot;</code></pre>
<p><em>Hint: the purpose of this step is to make sure everyone knows the column order of the design matrix so that you interprete the <span class="math inline">\(\beta\)</span> terms in the correct order.</em></p></li>
<li>Denote the coefficients obtained from the summary of your <code>lm()</code> call as <span class="math inline">\(\hat{\beta}_{0}\)</span> to <span class="math inline">\(\hat{\beta}_{5}\)</span> (in the order given by R). Write your interaction model out using subscript notation and should be in the form <span class="math display">\[y_{i}=\begin{cases}
??????? &amp; \;\;\textrm{if 4 cylinder}\\
??????? &amp; \;\;\textrm{if 6 cylinder}\\
??????? &amp; \;\;\textrm{if 8 cylinder}
\end{cases}\]</span> and give an interpretation for each <span class="math inline">\(\beta_{j}\)</span> value.
<ol style="list-style-type: lower-roman">
<li><span class="math inline">\(\hat{\beta}_0\)</span> = ???</li>
<li><span class="math inline">\(\hat{\beta}_1\)</span> = ???</li>
<li><span class="math inline">\(\hat{\beta}_2\)</span> = ???</li>
<li><span class="math inline">\(\hat{\beta}_3\)</span> = ???</li>
<li><span class="math inline">\(\hat{\beta}_4\)</span> = ???</li>
<li><span class="math inline">\(\hat{\beta}_5\)</span> = ???</li>
</ol></li>
<li><p>Using the full dataset, fit the model that predicts mpg using both weight and number of cylinders and their interaction using the command</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">model &lt;-<span class="st"> </span><span class="kw">lm</span>(mpg <span class="op">~</span><span class="st"> </span>wt<span class="op">*</span>cyl, <span class="dt">data=</span>mtcars)</code></pre></div>
<p>Create a vector of fitted values, add it to the data frame <code>mtcars</code> and then create a plot that includes the regression lines.</p></li>
<li><p>What is the estimated mpg of a 6-cylinder vehicle weighing 3.5 tons? What is the estimated mpg of a 8-cylinder vehicle weight 3.5 tons? Give the associated 95% confidence intervals. Calculate these using the <code>predict()</code> function. <em>Warning: When making the new data frame, make sure that R interprets cyl as a factor by either coercing it to a factor after creation or inputing the cylinder as a string (i.e. as “6” instead of 6).</em></p></li>
<li><p>Recalculate your answer to part (d) using the <code>glht()</code> function. Also give the estimate and confidence interval for the difference in mpg betwen the 8 and 6 cylinder vehicles that weight 3.5 tones? Is there a statistically significant difference in mpg at 3.5 tons?</p></li>
<li><p>Recalculate your answer to part (e) using the <code>emmeans()</code> function.</p></li>
<li><p>Are the slopes of the 8-cylinder and 6-cylinder vehicles statistically different? Use <code>glht()</code> to produce this result.</p></li>
<li><p>Recalculate your answer to part (g) using the <code>emtrends()</code> function.</p></li>
</ol></li>
</ol>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="4-analysis-of-covariance-ancova.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="6-diagnostics-and-transformations.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": false,
"twitter": false,
"google": false,
"linkedin": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/dereksonderegger/571/raw/master/05_Contrasts.Rmd",
"text": "Edit"
},
"download": [["Statistical_Methods_II.pdf", "PDF"], ["Statistical_Methods_II.epub", "EPUB"]],
"toc": {
"collapse": "section",
"scroll_highlight": true
},
"search": true
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
